@startuml
'https://plantuml.com/sequence-diagram

class Main {
    + main()
    + start()
}

class Controller {
    - addButton: Button
    - descriptionTextField: TextField
    - datePicker: DatePicker
    - itemList: ListView<AddItems>
    - isClicked: boolean
    - isDoubleClicked: boolean
}
class NewList {
}
class AddItems {
}
class RemoveList {
}
class EditList {
}
class DisplayList {
}
class SaveList {
}
class GetList {
}

javafx.Application <|-- Main
Controller -- Main
Controller -- NewList
Controller -- RemoveList
Controller -- EditList
Controller -- DisplayList
Controller -- SaveList
Controller -- GetList
Controller -- AddItems

@enduml